name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc clang libomp-dev
      - uses: actions/checkout@v4
      - run: cmake -S . -B build
      - run: cmake --build build
      - name: write - Moving data from UB to  KPC
        run: ./bin/fileio --mode=write --size-bytes=4096
      - name: write_fsync Moving data from UB to KPC to Disk
        run: ./bin/fileio --mode=write_fsync --size-bytes=4096
      - name: stdio Moving data from UB to SB to KPC
        run: ./bin/fileio --mode=stdio --size-bytes=4096
      - name: stdio_fsync Moving data from UB to SB to KPC to Disk
        run: ./bin/fileio --mode=stdio_fsync --size-bytes=4096
      - name: osync Moving data from UB to SB to KPC to Disk
        run: ./bin/fileio --mode=osync --size-bytes=4096
      - name: odirect Moving data from UB to Disk
        run: ./bin/fileio --mode=odirect --size-bytes=4096
